[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chicle"

# "non backwards compatible API changes.backwards compatible API changes.backwards compatible bug fixes"
version = "0.1.0"

authors = [
  { name="Gabriel López Vinielles", email="glopezv95@gmail.com" },
]
description = "A package to handle data cleaning and standardization."
readme = "README.md"

# >=3.9 if types list, dict, etc are used, >=3.10 if | used for types
requires-python = ">=3.9"

dependencies = [
  "polars",
  "fastexcel",
  "pandas",
  "pather @ git+https://github.com/glopezv95/pather.git"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = [
  "pytest"
]

[project.urls]
Homepage = "https://github.com/pypa/chicle"
Issues = "https://github.com/pypa/chicle/issues"

[tool.setuptools.packages.find]
where = ["src"]